### PR TITLE
* Adding AlNoorTV Video Addon

### PR DESCRIPTION
**Pull request by MoeHus**
* Removing broken AlBernameg addon
* Corrected Steps/link to add fusion repo
* Minor fix for addon_xml_generator.py

### CODE REVIEW

**Comment by MoeHus** [comment]
@bbk79 can you please take a look and accept this.

**Comment by bbk79** [comment]
Apologies for late response @MoeHus, is @hadynz around to have a look? It's just that I've been away from this one for so long that I pretty much have no clues about what is there.

**Comment by MoeHus** [comment]
I tweeted him  when I opened the pull request but haven't heard back yet.
You are the last person who changed this repo so I bet other maintainers don't remember either.

**Comment by MoeHus** [comment]
@Qwin @bisha77 @relax1000 Can anyone of you please take a look.

**Pull request merged**
